[[constraint]]
  branch = "master"
  name = "github.com/armon/go-radix"

[[constraint]]
  branch = "master"
  name = "github.com/jessevdk/go-flags"

[[constraint]]
  branch = "master"
  name = "github.com/julienschmidt/httprouter"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/copystructure"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[[constraint]]
  branch = "master"
  name = "github.com/renstrom/go-jump-consistent-hash"

[[constraint]]
  branch = "master"
  name = "github.com/segmentio/ksuid"

[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/sergi/go-diff"
  version = "1.0.0"
