# config for the HTTP api
http_api:
  addr: ":8081"

datasource_instances:
    # TODO: change to numbers?
    postgres1:
      storage_type: postgres
      storage_config:
        pg_string: user=postgres password=password sslmode=disable
